### PR TITLE
CLIENT SETNAME Operation

### PR DESCRIPTION
**Pull request by randysecrist**
This PR now just adds the client setname operation.  The gradle stuff will come in a separate PR as requested!

### CODE REVIEW

**Comment by fppt** [comment]
Hey thanks for the contribution! Would you mind putting the gradle build process in a separate PR? I will have to figure out how to release to sonatype repo via gradle and I would rather do that in a separate PR

**Comment by randysecrist** [comment]
Y; I can split it up.  Give me a couple of days to find a time slot.  Thanks!

**Comment by randysecrist** [comment]
Removed the gradle changes.  Will send those in another PR.  Looks like you all have upgraded to junit5 so I will need to update my branch accordingly.

**Comment by Celludriel** [comment]
Hey,

I'm currently hitting this limitation in our unit tests 

`Caused by: redis.clients.jedis.exceptions.JedisDataException: Unsupported operation 'client'
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:236)
	at redis.clients.jedis.Jedis.clientSetname(Jedis.java:3227)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:125)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 28 more`

is there any ETA on when this branch will be merged ?

**Comment by mwiede** [comment]
fyi I upgraded jedis version and changed testing setup to use testcontainers. compare https://github.com/mwiede/jedis-mock/tree/testcontainers

**Comment by randysecrist** [comment]
@fppt any reason for the hold up on merging this?  It should be clean + using junit5.

**Pull request merged**
